modLoader = "javafml"
loaderVersion = "[14,)"
license = "AGPL-3.0"
[[mods]]
modId = "limboauth-clientmod"
version = "${version}"
displayName = "LimboAuth ClientMod"
logoFile = "icon.png"
description = "Implement auto-login with the LimboAuth plugin, the client mod and a custom launcher"
[[dependencies.limboauth-clientmod]]
modId = "forge"
mandatory = true
versionRange = "[14,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.limboauth-clientmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.12.2,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.limboauth-clientmod]]
modId = "architectury"
mandatory = true
versionRange = "[0.0.0,)"
ordering = "NONE"
side = "BOTH"
